### TASK MANAGEMENT

### Get all tasks
GET http://localhost:3001/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNudDAwMCIsImlhdCI6MTY0OTY5MDE4MiwiZXhwIjoxNjQ5NjkzNzgyfQ.SI_ubos_pMPZL-8hFhy3rUVFeuGwoVEUtED0IqmiKpk

### Get all tasks with filter status
GET http://localhost:3001/tasks?status=OPEN HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNudDAwMCIsImlhdCI6MTY0ODA0MDY3MSwiZXhwIjoxNjQ4MDQ0MjcxfQ.LWd7ss1KSlI5LV9rO5xAFccsZW_NZWbj6P2rmeLWbm0

### Get all tasks with filter search
GET http://localhost:3001/tasks?search=BEER&status=OPEN HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNudDAwMCIsImlhdCI6MTY0NjIyNTYyNSwiZXhwIjoxNjQ2MjI5MjI1fQ.AGYYVhyc2Ho5fu5K03vD2TKSoSHVLrJZMDDs8YUwmWU

### Get task by Id
GET http://localhost:3001/tasks/283c7e0b-e126-4f55-a0f3-9b496e500094 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNudDAwMCIsImlhdCI6MTY0NjA1NDY5MiwiZXhwIjoxNjQ2MDU4MjkyfQ.eFXrjAoJSdwOIvWdr1vNqMhVXTMv46NJ2G3IdSWeDAQ

### Delete task
DELETE http://localhost:3001/tasks/283c7e0b-e126-4f55-a0f3-9b496e500094 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNudDAwMSIsImlhdCI6MTY0NjA1NDk1OSwiZXhwIjoxNjQ2MDU4NTU5fQ.gw3YhsfUaCiKneqPtyR0dxW-4YkW7k-BGEK8dwwBbY4

### Update status task
PATCH http://localhost:3001/tasks/fd287fa7-2348-4ba0-9f8a-1880758bd921/status HTTP/1.1
Content-Type: application/x-www-form-urlencoded

status=IN_PROGRESS


### Create Task
POST http://localhost:3001/tasks HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNudDAwMCIsImlhdCI6MTY0NjIyNTYyNSwiZXhwIjoxNjQ2MjI5MjI1fQ.AGYYVhyc2Ho5fu5K03vD2TKSoSHVLrJZMDDs8YUwmWU

{
    "title": "a title", 
    "description": "a description"
}

### Create Task
POST http://localhost:3001/tasks HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNudDAwMSIsImlhdCI6MTY0NjA1MzY0NCwiZXhwIjoxNjQ2MDU3MjQ0fQ.kBsq4ddI4_rNfRYYJTjNnv4fdod8Ru2oUxoeNUbwwLA

{
    "title": "from user 2", 
    "description": "a beer"
}

### Create Empty values Task
POST http://localhost:3001/tasks HTTP/1.1
content-type: application/json

{
    "title": "", 
    "description": ""
}

###AUTH#######################

### Create User - signup
POST http://localhost:3001/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "cnt001", 
    "password": "Password1!"
}


### Login - signin
POST http://localhost:3001/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "cnt000", 
    "password": "Password1!"
}

###
-----------------------------------------------------

PROD

### Get all tasks
GET https://task-management-cnt000.herokuapp.com/tasks HTTP/1.1
Authorization: Bearer e

### Create User - signup
POST https://task-management-cnt000.herokuapp.com/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "cnt000", 
    "password": "Password1!"
}


### Login - signin
POST https://task-management-cnt000.herokuapp.com/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "cnt000", 
    "password": "Password1!"
}

### Create Task
POST https://task-management-cnt000.herokuapp.com/tasks HTTP/1.1
content-type: application/json
Authorization: Bearer e

{
    "title": "another task to do in this life", 
    "description": "nichilism phase 2"
}