### TASK MANAGEMENT

### Get all tasks
GET http://localhost:3001/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNudDAwMCIsImlhdCI6MTY0NTE4OTEzNiwiZXhwIjoxNjQ1MTkyNzM2fQ.OHd9Re3M2RimeO9MTKBa82s7wm_8FB92-T07cC7rD10

### Get all tasks with filter status
GET http://localhost:3001/tasks?status=OPEN HTTP/1.1

### Get all tasks with filter search
GET http://localhost:3001/tasks?search=BEER&status=OPEN HTTP/1.1

### Get task by Id
GET http://localhost:3001/tasks/fd287fa7-2348-4ba0-9f8a-1880758bd921 HTTP/1.1

### Delete task
DELETE http://localhost:3001/tasks/951d5b82-9408-4ede-af24-16198b1f813d HTTP/1.1

### Update status task
PATCH http://localhost:3001/tasks/fd287fa7-2348-4ba0-9f8a-1880758bd921/status HTTP/1.1
Content-Type: application/x-www-form-urlencoded

status=IN_PROGRESS


### Create Task
POST http://localhost:3001/tasks HTTP/1.1
content-type: application/json

{
    "title": "a title", 
    "description": "a description"
}

### Create Task
POST http://localhost:3001/tasks HTTP/1.1
content-type: application/json

{
    "title": "evening", 
    "description": "a beer"
}

### Create Empty values Task
POST http://localhost:3001/tasks HTTP/1.1
content-type: application/json

{
    "title": "", 
    "description": ""
}

###AUTH#######################

### Create User - signup
POST http://localhost:3001/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "cnt003", 
    "password": "Password1!"
}


### Login - signin
POST http://localhost:3001/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "cnt000", 
    "password": "Password1!"
}